from .person import Person
from .treningssenter import Treningssenter
from .treningsokt import Treningsokt
from .ovelse import Ovelse
from .apparat import Apparat
from .ovelse_pa_apparat import Ovelse_pa_apparat
from .ovelsegruppe import Ovelsegruppe
from .ovelse_i_ovelsegruppe import Ovelse_i_ovelsegruppe
from .apparat_ovelse_relasjon import ApparatOvelseRelasjon
from .ovelse_treningsokt_relasjon import OvelseTreningsoktRelasjon